version: '3.8'

services:
  app:
    build: .
    container_name: pathfinder-app
    ports:
      - "9000:9000"
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - pathfinder-network

  postgres:
    image: postgres:17.2
    container_name: pathfinder-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pathfinder
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pathfinder-network

volumes:
  postgres_data:

networks:
  pathfinder-network:
    driver: bridge 